### ISSUE TITLE
index fix

### ISSUE THREAD

**Issue by sangjinshin** [ovallner/ovallner.github.io#1]
Can you move the welcom h2 out of the div? i put div there to make styling multiple paragraphs underneath easier instead of adding p, h2, h3, etc to the stylesheet. Also you cant do that because that means the all the p and h2 created in other webpages will have the same styling which we don't want. we want to put each section under div to make styling each and specific part of the website easy

**Comment by ovallner** [comment]
I think it's good that they have the same styling though. We want a
consistent look, so it's good if all the font, size, etc. changes are
applied to everything.

**Comment by sangjinshin** [comment]
you cant move margins and make it apply to every page unless u want every paragraph to be in the same location for every page
